# For testing and development.

---
services:
  runner:
#    image: geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux8}-ansible:latest
    image: jonpugh/github-runner
    hostname: ${DOCKER_HOSTNAME:-localhost.runner}
    volumes:
      - ./:/github-runner
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_REPOSITORY: jonpugh/github-runner
    entrypoint: /github-runner/github-runner
    build: ./