name: Demo
on:
  push:
    branches: [ "feature/docker-container" ]
  workflow_dispatch:

jobs:
  demo:
    name: Demonstrate runner
    runs-on: "runner${{ matrix.runner }}@localhost"
    strategy:
      matrix:
        runner: [1, 2, 3, 4, 5]
    steps:
      - name: Debug
        run: |
          echo "Who am I: $(whoami)"
          echo "Hostname: $(hostname -f)"
          echo "Environment:"
          env
          ping google.com -c10
